live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x181818'
foreground = '0xd8d8d8'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x181818'
cursor = '0xd8d8d8'

# Normal colors
[colors.normal]
black = '0x181818'
red = '0xab4642'
green = '0xa1b56c'
yellow = '0xf7ca88'
blue = '0x7cafc2'
magenta = '0xba8baf'
cyan = '0x86c1b9'
white = '0xd8d8d8'

# Bright colors
[colors.bright]
black = '0x585858'
red = '0xdc9656'
green = '0x282828'
yellow = '0x383838'
blue = '0xb8b8b8'
magenta = '0xe8e8e8'
cyan = '0xa16946'
white = '0xf8f8f8'

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "Agave Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Agave Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Agave Nerd Font"
style = "Italic"

[font.normal]
family = "Agave Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 500
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false

[window.padding]
x = 0
y = 0
