live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = '#161821'
foreground = '#d2d4de'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#161821'
cursor = '#c6c8d1'

# Normal colors
[colors.normal]
black = '#161821'
red = '#e27878'
green = '#b4be82'
yellow = '#e2a478'
blue = '#84a0c6'
magenta = '#a093c7'
cyan = '#89b8c2'
white = '#c6c8d1'

# Bright colors
[colors.bright]
black = '#6b7089'
red = '#e98989'
green = '#c0ca8e'
yellow = '#e9b189'
blue = '#91acd1'
magenta = '#ada0d3'
cyan = '#95c4ce'
white = '#d2d4de'

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 500
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false

[window.padding]
x = 0
y = 0
