live_config_reload = true

[colors.primary]
background = '#151515'
foreground = '#a9a9a9'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#393939'
cursor = '#a9a9a9'

# Normal colors
[colors.normal]
black = '#393939'
red = '#ca674a'
green = '#96a967'
yellow = '#d3a94a'
blue = '#5778c1'
magenta = '#9c35ac'
cyan = '#6eb5f3'
white = '#a9a9a9'

# Bright colors
[colors.bright]
black = '#535551'
red = '#ea2828'
green = '#87dd32'
yellow = '#f7e44d'
blue = '#6f9bca'
magenta = '#a97ca4'
cyan = '#32dddd'
white = '#e9e9e7'

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "agave"
style = "Bold"

[font.bold_italic]
family = "agave"
style = "Bold Italic"

[font.italic]
family = "agave"
style = "Italic"

[font.normal]
family = "agave"
style = "Medium"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 500
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false

[window.padding]
x = 0
y = 0
