[general]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1d2021'
foreground = '0xd5c4a1'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1d2021'
cursor = '0xd5c4a1'

# Normal colors
[colors.normal]
black = '0x1d2021'
red = '0xfb4934'
green = '0xb8bb26'
yellow = '0xfabd2f'
blue = '0x83a598'
magenta = '0xd3869b'
cyan = '0x8ec07c'
white = '0xd5c4a1'

# Bright colors
[colors.bright]
black = '0x665c54'
red = '0xfe8019'
green = '0x3c3836'
yellow = '0x504945'
blue = '0xbdae93'
magenta = '0xebdbb2'
cyan = '0xd65d0e'
white = '0xfbf1c7'

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "Ubuntu Mono"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono"
style = "Bold"

[font.italic]
family = "Ubuntu Mono"
style = "Medium"

[font.normal]
family = "Ubuntu Mono"
style = "Medium"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 500
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false

[window.padding]
x = 0
y = 0
