live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x2e3440'
foreground = '0xe5e9f0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2e3440'
cursor = '0xe5e9f0'

# Normal colors
[colors.normal]
black = '0x2e3440'
red = '0xbf616a'
green = '0xa3be8c'
yellow = '0xebcb8b'
blue = '0x81a1c1'
magenta = '0xb48ead'
cyan = '0x88c0d0'
white = '0xe5e9f0'

# Bright colors
[colors.bright]
black = '0x4c566a'
red = '0xd08770'
green = '0x3b4252'
yellow = '0x434c5e'
blue = '0xd8dee9'
magenta = '0xeceff4'
cyan = '0x5e81ac'
white = '0x8fbcbb'

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Comic Shanns Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Comic Shanns Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Comic Shanns Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Comic Shanns Mono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 500
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false

[window.padding]
x = 0
y = 0
